version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    
    working_directory: /go/src/github.com/mlabouardy/docker-eb-ci-mon

    steps:
      - checkout

      - setup_remote_docker

      - run:
         name: Install AWS CLI
         command: |
          apt-get update
          apt-get install -y awscli

      - run:
          name: Test
          command: go test
      
      - run:
          name: Build
          command: docker build -t mlabouardy/avengers:latest .
      
      - run:
          name: Push
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker tag mlabouardy/avengers:latest mlabouardy/avengers:${CIRCLE_SHA1}
            docker push mlabouardy/avengers:latest
            docker push mlabouardy/avengers:${CIRCLE_SHA1}
      
      - run:
          name: Deploy
          command: |
            zip deployment-${CIRCLE_SHA1}.zip *
            aws elasticbeanstalk create-application-version --application-name avengers \
                --version-label ${CIRCLE_SHA1} --source-bundle S3Bucket="avengers-docker-eb",S3Key="deployment-${CIRCLE_SHA1}.zip" --region eu-west-3
            aws elasticbeanstalk update-environment --application-name avengers \
                --environment-name staging --version-label ${CIRCLE_SHA1} --region eu-west-3