version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    
    working_directory: /go/src/github.com/mlabouardy/docker-eb-ci-mon

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Test
          command: go test
      
      - run:
          name: Build
          command: docker build -t mlabouardy/avengers:latest .
      
      - run:
          name: Push
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker tag mlabouardy/avengers:latest mlabouardy/avengers:${CIRCLE_SHA1}
            docker push mlabouardy/avengers:latest
            docker push mlabouardy/avengers:${CIRCLE_SHA1}
      
      - run:
          name: Deploy
          command: |
            deploy to eb